### ISSUE TITLE
Image width

### ISSUE THREAD

**Issue by andeElliott** [UofGAnalytics/build-coursework#141]
Is there anyway to make image width the same as the text width? 

Mostly it is fine, but there is a few places where this means that the images are not as readable as the versions in the Boldtools version which is annoying as it makes it less accessible?

**Comment by dmca-glasgow** [comment]
Yes and no.  

First of all, images shouldn't have text in them, although plots are an exception.

Second, as web pages are responsive, or need to have a fluid layout depending on the width of the browser/screen, it becomes clear that images and text can not be treated the same.  Images have an intrinsic width and height ratio, whereas text can flow more dynamically.  You'll see at some widths the images and text are the same width, but at others they're not.  This is a compromise as in some cases, full-width images would be too tall to be readable.  Due to how web technologies work, it's not easy to make exceptions due to the _height_ of something, like a square or portrait image, you have to make calculated guesses based on the width only and assume there will be a scroll bar.
